#!/usr/bin/env bash
API="https://silver-puffpuff-8a67de.netlify.app/.netlify/functions/wix-migrate?action=createredirects"

echo "=== Batch 1/11 (15) ==="
curl -sX POST "$API" -H "Content-Type: application/json" --data '{"redirects": [{"source": "/baater", "destination": "/buy", "code": 301}, {"source": "/post/kjøp-av-båt-i-utlandet", "destination": "/blog/kjøp-av-båt-i-utlandet", "code": 301}, {"source": "/Baater/fjord-terne-24", "destination": "/boat/fjord-terne-24", "code": 301}, {"source": "/post/huskeliste-kjøp-av-bruktbåt", "destination": "/blog/huskeliste-kjøp-av-bruktbåt", "code": 301}, {"source": "/Baater/nimbus-300r", "destination": "/boat/nimbus-300r", "code": 301}, {"source": "/Baater/nimbus-250-r", "destination": "/boat/nimbus-250-r", "code": 301}, {"source": "/Baater/seabreacher-z", "destination": "/boat/seabreacher-z", "code": 301}, {"source": "/Baater/sandvik-945", "destination": "/boat/sandvik-945", "code": 301}, {"source": "/Baater/nimbus-230-r", "destination": "/boat/nimbus-230-r", "code": 301}, {"source": "/Baater/riva-dolceriva-48", "destination": "/boat/riva-dolceriva-48", "code": 301}, {"source": "/nimbus250", "destination": "/buy?filter=nimbus", "code": 301}, {"source": "/Baater/scand-baltic-29", "destination": "/boat/scand-baltic-29", "code": 301}, {"source": "/Baater/riviera-925-fly", "destination": "/boat/riviera-925-fly", "code": 301}, {"source": "/Baater/nordkapp-760-noblesse", "destination": "/boat/nordkapp-760-noblesse", "code": 301}, {"source": "/Baater/windy-7500", "destination": "/boat/windy-7500", "code": 301}]}' | jq ".ok, .failed"

echo "=== Batch 2/11 (15) ==="
curl -sX POST "$API" -H "Content-Type: application/json" --data '{"redirects": [{"source": "/Baater/nidelv-725-sport", "destination": "/boat/nidelv-725-sport", "code": 301}, {"source": "/Baater/arctic-blue-27-mkii", "destination": "/boat/arctic-blue-27-mkii", "code": 301}, {"source": "/Baater/goldfish-50-ocean", "destination": "/boat/goldfish-50-ocean", "code": 301}, {"source": "/Baater/beneteau-swift-trawler-34", "destination": "/boat/beneteau-swift-trawler-34", "code": 301}, {"source": "/Baater/nimbus-35-nova-ht-", "destination": "/boat/nimbus-35-nova-ht", "code": 301}, {"source": "/Baater/windy-35-khamsin", "destination": "/boat/windy-35-khamsin", "code": 301}, {"source": "/Baater/targa-27.1", "destination": "/boat/targa-27.1", "code": 301}, {"source": "/post/sandvik-945-for-salg", "destination": "/blog/sandvik-945-for-salg", "code": 301}, {"source": "/Baater/nimbus-230r", "destination": "/boat/nimbus-230r", "code": 301}, {"source": "/Baater/windy-44-chinook", "destination": "/boat/windy-44-chinook", "code": 301}, {"source": "/BaaterTilSalgs", "destination": "/buy", "code": 301}, {"source": "/Baater/bavaria-40-cruiser", "destination": "/boat/bavaria-40-cruiser", "code": 301}, {"source": "/Baater/nordic-ocean-craft-catamaran", "destination": "/boat/nordic-ocean-craft-catamaran", "code": 301}, {"source": "/Baater/marex-280-holiday", "destination": "/boat/marex-280-holiday", "code": 301}, {"source": "/post/nidelv-725-sport-for-salg", "destination": "/blog/nidelv-725-sport-for-salg", "code": 301}]}' | jq ".ok, .failed"

echo "=== Batch 3/11 (15) ==="
curl -sX POST "$API" -H "Content-Type: application/json" --data '{"redirects": [{"source": "/post/hvilken-goldfish-er-best-sammenligner-3-generasjoner-goldfish-23-tender", "destination": "/blog/hvilken-goldfish-er-best-sammenligner-3-generasjoner-goldfish-23-tender", "code": 301}, {"source": "/Baater/axopar-28-cabin", "destination": "/boat/axopar-28-cabin", "code": 301}, {"source": "/Baater/nimbus-34-nova", "destination": "/boat/nimbus-34-nova", "code": 301}, {"source": "/Baater/askeladden-c83-cruiser", "destination": "/boat/askeladden-c83-cruiser", "code": 301}, {"source": "/Baater/nimbus-320-coupé", "destination": "/boat/nimbus-320-coupé", "code": 301}, {"source": "/Baater/princess-25m", "destination": "/boat/princess-25m", "code": 301}, {"source": "/Baater/goldfish-23-tender-mkiii", "destination": "/boat/goldfish-23-tender-mkiii", "code": 301}, {"source": "/Baater/askeladden-c80-cruiser", "destination": "/boat/askeladden-c80-cruiser", "code": 301}, {"source": "/Baater/bostrøm-31-mki", "destination": "/boat/bostrøm-31-mki", "code": 301}, {"source": "/Baater/nimbus-33-nova", "destination": "/boat/nimbus-33-nova", "code": 301}, {"source": "/post/solgt-nordic-star-32", "destination": "/blog/solgt-nordic-star-32", "code": 301}, {"source": "/Baater/hydrolift-s24-diablo", "destination": "/boat/hydrolift-s24-diablo", "code": 301}, {"source": "/Baater/aquador-26-dc", "destination": "/boat/aquador-26-dc", "code": 301}, {"source": "/Baater/bavaria-44-vision", "destination": "/boat/bavaria-44-vision", "code": 301}, {"source": "/Baater/candela-c-8", "destination": "/boat/candela-c-8", "code": 301}]}' | jq ".ok, .failed"

echo "=== Batch 4/11 (15) ==="
curl -sX POST "$API" -H "Content-Type: application/json" --data '{"redirects": [{"source": "/Baater/bavaria-40-vision", "destination": "/boat/bavaria-40-vision", "code": 301}, {"source": "/Baater/fleming-58", "destination": "/boat/fleming-58", "code": 301}, {"source": "/Baater/nimbus-30s", "destination": "/boat/nimbus-30s", "code": 301}, {"source": "/Baater/beneteau-41-swift-trawler-sedan", "destination": "/boat/beneteau-41-swift-trawler-sedan", "code": 301}, {"source": "/Baater/windy-26-kharma", "destination": "/boat/windy-26-kharma", "code": 301}, {"source": "/Baater/beneteau-figaro-2", "destination": "/boat/beneteau-figaro-2", "code": 301}, {"source": "/post/solgt-2000-viksund-290-310-st-cruz", "destination": "/blog/solgt-2000-viksund-290-310-st-cruz", "code": 301}, {"source": "/Baater/dufour-385-grand-large", "destination": "/sold", "code": 301}, {"source": "/Baater/anytec-860-spd", "destination": "/sold", "code": 301}, {"source": "/Baater/windy-37-grand-mistral", "destination": "/sold", "code": 301}, {"source": "/Baater/fairline-phantom-48", "destination": "/boat/fairline-phantom-48", "code": 301}, {"source": "/Baater/nimbus-29-nova", "destination": "/boat/nimbus-29-nova", "code": 301}, {"source": "/baatmegler", "destination": "/om-oss", "code": 301}, {"source": "/Baater/paragon-25-cabin", "destination": "/boat/paragon-25-cabin", "code": 301}, {"source": "/Baater/boston-whaler-190-outrage", "destination": "/sold", "code": 301}]}' | jq ".ok, .failed"

echo "=== Batch 5/11 (15) ==="
curl -sX POST "$API" -H "Content-Type: application/json" --data '{"redirects": [{"source": "/Baater/askeladden-c83", "destination": "/boat/askeladden-c83", "code": 301}, {"source": "/Baater/nord-west-370-coupé", "destination": "/sold", "code": 301}, {"source": "/Baater/nimbus-305-drophead", "destination": "/boat/nimbus-305-drophead", "code": 301}, {"source": "/Baater/nimbus-280-coupé", "destination": "/sold", "code": 301}, {"source": "/Baater/jeanneau-so-49-ds", "destination": "/sold", "code": 301}, {"source": "/Baater/marex-375", "destination": "/boat/marex-375", "code": 301}, {"source": "/Baater/sargo-25", "destination": "/sold", "code": 301}, {"source": "/Baater/jeanneau-sun-odyssey-36i", "destination": "/boat/jeanneau-sun-odyssey-36i", "code": 301}, {"source": "/Baater/chris-craft-25-corsair", "destination": "/boat/chris-craft-25-corsair", "code": 301}, {"source": "/Baater/cormate-t-27", "destination": "/boat/cormate-t-27", "code": 301}, {"source": "/Baater/bavaria-37-ac", "destination": "/sold", "code": 301}, {"source": "/Baater/colin-archer-40", "destination": "/boat/colin-archer-40", "code": 301}, {"source": "/Baater/windy-35-khamsin-2008-d6-370", "destination": "/sold", "code": 301}, {"source": "/Baater/quicksilver-905-pilothouse", "destination": "/sold", "code": 301}, {"source": "/Baater/axopar-28-open", "destination": "/boat/axopar-28-open", "code": 301}]}' | jq ".ok, .failed"

echo "=== Batch 6/11 (15) ==="
curl -sX POST "$API" -H "Content-Type: application/json" --data '{"redirects": [{"source": "/Baater/marex-370-acc", "destination": "/boat/marex-370-acc", "code": 301}, {"source": "/Baater/marex-360-cc", "destination": "/boat/marex-360-cc", "code": 301}, {"source": "/Baater/goldfish-29-sport---2020", "destination": "/sold", "code": 301}, {"source": "/kjope-bat", "destination": "/buy", "code": 301}, {"source": "/Baater/nordkapp-720-noblesse", "destination": "/boat/nordkapp-720-noblesse", "code": 301}, {"source": "/Baater/goldfish-28-rib", "destination": "/boat/goldfish-28-rib", "code": 301}, {"source": "/Baater/goldfish-29-sport", "destination": "/boat/goldfish-29-sport", "code": 301}, {"source": "/Baater/grand-banks-52-europa", "destination": "/sold", "code": 301}, {"source": "/Baater/goldfish-30-sport---diesel", "destination": "/sold", "code": 301}, {"source": "/Baater/fjord-40-open", "destination": "/boat/fjord-40-open", "code": 301}, {"source": "/Baater/bavaria-s36-ht", "destination": "/boat/bavaria-s36-ht", "code": 301}, {"source": "/Baater/elan-37", "destination": "/boat/elan-37", "code": 301}, {"source": "/Baater/goldfish-38-supersport", "destination": "/boat/goldfish-38-supersport", "code": 301}, {"source": "/Baater/bayliner-avanti-4085-express-cruiser", "destination": "/sold", "code": 301}, {"source": "/Baater/nordkapp-705-enduro", "destination": "/boat/nordkapp-705-enduro", "code": 301}]}' | jq ".ok, .failed"

echo "=== Batch 7/11 (15) ==="
curl -sX POST "$API" -H "Content-Type: application/json" --data '{"redirects": [{"source": "/Baater/bavaria-35-sport", "destination": "/boat/bavaria-35-sport", "code": 301}, {"source": "/Baater/grandezza-31-oc", "destination": "/boat/grandezza-31-oc", "code": 301}, {"source": "/Baater/dufour-385-gl", "destination": "/sold", "code": 301}, {"source": "/Baater/flipper-760-dc", "destination": "/sold", "code": 301}, {"source": "/Baater/nimbus-w9", "destination": "/boat/nimbus-w9", "code": 301}, {"source": "/Baater/axopar-25-cross-bow", "destination": "/boat/axopar-25-cross-bow", "code": 301}, {"source": "/Baater/nimbus-250r-mkii", "destination": "/boat/nimbus-250r-mkii", "code": 301}, {"source": "/Baater/goldfish-28-tender", "destination": "/boat/goldfish-28-tender", "code": 301}, {"source": "/Baater/nimbus-w9-t-top", "destination": "/boat/nimbus-w9-t-top", "code": 301}, {"source": "/Baater/nimbus-300r---2005-modell", "destination": "/sold", "code": 301}, {"source": "/Baater/nimbus-35-nova-ht", "destination": "/boat/nimbus-35-nova-ht", "code": 301}, {"source": "/Baater/m/y-in-excess", "destination": "/sold", "code": 301}, {"source": "/Baater/1912-anker-&-jensen-9mr-flirt-iv", "destination": "/sold", "code": 301}, {"source": "/Baater/targa-44-fly", "destination": "/sold", "code": 301}, {"source": "/Baater/goldfish-23-tender---2018", "destination": "/sold", "code": 301}]}' | jq ".ok, .failed"

echo "=== Batch 8/11 (15) ==="
curl -sX POST "$API" -H "Content-Type: application/json" --data '{"redirects": [{"source": "/Baater/nimbus-t9", "destination": "/boat/nimbus-t9", "code": 301}, {"source": "/Baater/jeanneau-sun-odyssey-519", "destination": "/boat/jeanneau-sun-odyssey-519", "code": 301}, {"source": "/Baater/brig-eagle-8---2022", "destination": "/boat/brig-eagle-8-2022", "code": 301}, {"source": "/Baater/nimbus-35-nova-ht---2008", "destination": "/sold", "code": 301}, {"source": "/Baater/goldfish-x12-endurance", "destination": "/sold", "code": 301}, {"source": "/Baater/fairline-targa-37", "destination": "/boat/fairline-targa-37", "code": 301}, {"source": "/Baater/azimut-47-fly", "destination": "/sold", "code": 301}, {"source": "/Baater/bavaria-360-sport-open", "destination": "/boat/bavaria-360-sport-open", "code": 301}, {"source": "/Baater/nimbus-320-coupè---2003", "destination": "/sold", "code": 301}, {"source": "/selge-bat", "destination": "/", "code": 301}, {"source": "/Baater/ibiza-881-t-special-edition", "destination": "/sold", "code": 301}, {"source": "/Baater/skorgenes-350-fly", "destination": "/sold", "code": 301}, {"source": "/Baater/goldfish-38-sport", "destination": "/sold", "code": 301}, {"source": "/Baater/windy-39-camira", "destination": "/boat/windy-39-camira", "code": 301}, {"source": "/Baater/axopar-37-cabin", "destination": "/boat/axopar-37-cabin", "code": 301}]}' | jq ".ok, .failed"

echo "=== Batch 9/11 (15) ==="
curl -sX POST "$API" -H "Content-Type: application/json" --data '{"redirects": [{"source": "/Baater/grand-banks-47-heritage-eu", "destination": "/sold", "code": 301}, {"source": "/Baater/chris-craft-carina-21", "destination": "/sold", "code": 301}, {"source": "/Baater/windy-28-ghibli---2001", "destination": "/sold", "code": 301}, {"source": "/Baater/axopar-37-sports-cabin", "destination": "/sold", "code": 301}, {"source": "/Baater/bavaria-37-cruiser", "destination": "/boat/bavaria-37-cruiser", "code": 301}, {"source": "/Baater/modesty-33-sc", "destination": "/sold", "code": 301}, {"source": "/Baater/azimut-atlantis-40-ht", "destination": "/sold", "code": 301}, {"source": "/Baater/nimbus-250r", "destination": "/boat/nimbus-250r", "code": 301}, {"source": "/Baater/goldfish-30-sport---2022", "destination": "/sold", "code": 301}, {"source": "/Baater/cormate-35-chase", "destination": "/sold", "code": 301}, {"source": "/Baater/marex-310-sun-cruiser", "destination": "/boat/marex-310-sun-cruiser", "code": 301}, {"source": "/Baater/windy-28-ghibli-kad-300", "destination": "/sold", "code": 301}, {"source": "/Baater/princess-415", "destination": "/boat/princess-415", "code": 301}, {"source": "/Baater/saffier-se-33-ud", "destination": "/sold", "code": 301}, {"source": "/Baater/marex-360-cc---2022", "destination": "/sold", "code": 301}]}' | jq ".ok, .failed"

echo "=== Batch 10/11 (15) ==="
curl -sX POST "$API" -H "Content-Type: application/json" --data '{"redirects": [{"source": "/Baater/jeanneau-cap-camarat-925-wa", "destination": "/boat/jeanneau-cap-camarat-925-wa", "code": 301}, {"source": "/Baater/chris-craft-28-corsair", "destination": "/boat/chris-craft-28-corsair", "code": 301}, {"source": "/Baater/bavaria-37-cruiser---2006", "destination": "/sold", "code": 301}, {"source": "/Baater/sunseeker-44-camargue", "destination": "/boat/sunseeker-44-camargue", "code": 301}, {"source": "/Baater/nimbus-t11", "destination": "/boat/nimbus-t11", "code": 301}, {"source": "/Baater/glastron-gs-259", "destination": "/boat/glastron-gs-259", "code": 301}, {"source": "/Baater/goldfish-30-sport", "destination": "/boat/goldfish-30-sport", "code": 301}, {"source": "/Baater/hanse-355", "destination": "/boat/hanse-355", "code": 301}, {"source": "/verdivurdering", "destination": "/", "code": 301}, {"source": "/Baater/goldfish-23-tender", "destination": "/boat/goldfish-23-tender", "code": 301}, {"source": "/Baater/hydrolift-x-32s-r", "destination": "/boat/hydrolift-x-32s-r", "code": 301}, {"source": "/Baater/nordkapp-905-grand-coupe", "destination": "/boat/nordkapp-905-grand-coupe", "code": 301}, {"source": "/Baater/fairline-squadron-55", "destination": "/boat/fairline-squadron-55", "code": 301}, {"source": "/Baater/seaside-23", "destination": "/boat/seaside-23", "code": 301}, {"source": "/Baater/pershing-64", "destination": "/boat/pershing-64", "code": 301}]}' | jq ".ok, .failed"

echo "=== Batch 11/11 (9) ==="
curl -sX POST "$API" -H "Content-Type: application/json" --data '{"redirects": [{"source": "/Baater/wolstenholme-38", "destination": "/boat/wolstenholme-38", "code": 301}, {"source": "/Baater/lagoon-560-s2", "destination": "/boat/lagoon-560-s2", "code": 301}, {"source": "/Baater/carver-396-aft-cabin", "destination": "/boat/carver-396-aft-cabin", "code": 301}, {"source": "/Baater/grandezza-27s", "destination": "/boat/grandezza-27s", "code": 301}, {"source": "/Baater/beneteau-oceanis-37", "destination": "/boat/beneteau-oceanis-37", "code": 301}, {"source": "/Baater/saxdor-320-gtc", "destination": "/boat/saxdor-320-gtc", "code": 301}, {"source": "/Baater/goldfish-29-rib-tender", "destination": "/boat/goldfish-29-rib-tender", "code": 301}, {"source": "/Baater/cranchi-mediterrane-47", "destination": "/boat/cranchi-mediterrane-47", "code": 301}, {"source": "/Baater/ibiza-811-touring", "destination": "/boat/ibiza-811-touring", "code": 301}]}' | jq ".ok, .failed"

echo DONE